# ----------------------------------- PlayerHeads Configuration -----------------------------------
# Defaults/explanation:
# droprate: 0.05                [0.0 -> 1.0]    Chance that a trophy will drop when a 
#                                               player dies (1 is 100%, 0 is never)
# lootingrate: 0.2              [0.0 -> 1.0]    Increases all droprates by lootingrate percent per 
#                                               looting level when a enchanted weapon is used
# {MobName}droprate: 0.005      [0.0 -> 1.0]    Chance that a mob trophy will drop when it dies
# language: default             [default, es]   Change the language configured (default is english 
#                                               and es is Spanish). You can edit the language file
droprate: 0.05
lootingrate: 0.2
language: default
creeperdroprate: 0.005
zombiedroprate: 0.002
skeletondroprate: 0.002
witherskeletondroprate: 0.025
spiderdroprate: 0.002
endermandroprate: 0.002
blazedroprate: 0.002
horsedroprate: 0.002
squiddroprate: 0.005
silverfishdroprate: 0.005
enderdragondroprate: 0.05
slimedroprate: 0.001
irongolemdroprate: 0.005
mushroomcowdroprate: 0.002
batdroprate: 0.005
pigzombiedroprate: 0.002
snowmandroprate: 0.002
ghastdroprate: 0.005
pigdroprate: 0.002
villagerdroprate: 0.002
sheepdroprate: 0.002
cowdroprate: 0.002
chickendroprate: 0.002
ocelotdroprate: 0.005
witchdroprate: 0.005
magmacubedroprate: 0.001
wolfdroprate: 0.002
cavespiderdroprate: 0.002
rabbitdroprate: 0.002
guardiandroprate: 0.025
huskdroprate: 0.004
shulkerdroprate: 0.006
vexdroprate: 0.002
polarbeardroprate: 0.002
witherdroprate: 1
skeletonhorsedroprate: 0.004 
vindicatordroprate: 0.005
straydroprate: 0.003
llamadroprate: 0.005
evokerdroprate: 0.006
donkeydroprate: 0.005
muledroprate: 0.005
elderguardiandroprate: 0.003
endermitedroprate: 0.003
zombiehorsedroprate: 0.003
zombievillagerdroprate: 0.003
parrotreddroprate: 0.005
parrotbluedroprate: 0.005
parrotcyandroprate: 0.005
parrotgreendroprate: 0.005
parrotgraydroprate: 0.005
